server.port: 9090

spring:
  security:
    user: # spring security 기본 아이디와 암호
      name: user
      password: 1234
  h2:
    console:
      path: /h2-console
      enabled: true
  devtools:
    livereload:
      enabled: true